# Generated by Django 2.2.10 on 2020-09-23 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('zipcode', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('garage', models.BooleanField()),
                ('sqft', models.IntegerField()),
                ('Lot_size', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_published', models.BooleanField()),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('photo1', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('photo2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('list_date', models.DateTimeField()),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realtors.Realtor')),
            ],
            options={
                'ordering': ('-list_date',),
            },
        ),
    ]
